# Generated by Django 4.0.7 on 2022-10-18 14:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('avatar', models.ImageField(upload_to='collection/avatar')),
                (
                    'title',
                    models.CharField(
                        max_length=30,
                        validators=[
                            django.core.validators.RegexValidator('^[a-zA-Z ]+$')
                        ],
                    ),
                ),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True, default='')),
                (
                    'author',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
