# Generated by Django 4.0.7 on 2022-10-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['pk']},
        ),
        migrations.RemoveField(
            model_name='collection',
            name='id',
        ),
        migrations.AlterField(
            model_name='collection',
            name='slug',
            field=models.SlugField(primary_key=True, serialize=False),
        ),
    ]
