area:cicd:
  - ".github/**/*"
  - "docker/**/*"
  - "envs/*"
  - "nginx/*"
  - ".coveragerc"
  - ".dockerignore"
  - ".pre-commit-config.yaml"
  - "codecov.yml"
  - "pyproject.toml"
  - "setup.cfg"
  - ".run"
  - "Dockerfile"

area:api:
  - "api/**/*"
  - "app/**/*"

area:requirements:
  - "requirements.txt"

area:tests:
  - "app/*/tests/**/*"
