name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: ' Solved tasks'
    labels:
      - 'task'

  - title: ' Fixed bugs'
    labels:
      - 'bug'

  - title: ' Added tests'
    labels:
      - 'test'

  - title: ' Updated dependencies'
    labels:
      - 'dependencies'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes
  
  $CHANGES
