name-template: 'v$RESOLVED_VERSION 🔥'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '🚀 Solved tasks'
    labels:
      - 'task'

  - title: '🔧 Fixed bugs'
    labels:
      - 'bug'

  - title: '☂️ Added tests'
    labels:
      - 'test'

  - title: '⬆️ Updated dependencies'
    labels:
      - 'dependencies'

  - title: '♾️ Upgraded CI/CD'
    labels:
      - 'cicd'

exclude-contributors:
  - dependabot
  - github-actions[bot]
  - pre-commit-ci

change-template: |
  - $TITLE in #$NUMBER

template: |
  # Changes
  
  $CHANGES
  
  # Contributors
  
  $CONTRIBUTORS
