categories:
  - title: '🚀 Solved tasks'
    labels:
      - 'task'

  - title: '💪🏻 Improved'
    labels:
      - 'enhancement'

  - title: '🔧 Fixed bugs'
    labels:
      - 'bug'

  - title: '☂️ Added tests'
    labels:
      - 'test'

  - title: '⬆️ Updated dependencies'
    labels:
      - 'dependencies'

  - title: '♾️ Upgraded CI/CD'
    labels:
      - 'cicd'

exclude-contributors:
  - dependabot
  - dependabot[bot]
  - github-actions[bot]

change-template: |
  - $TITLE in #$NUMBER
  - - $BODY

template: |
  # Changes
  
  $CHANGES
  
  # Contributors
  
  $CONTRIBUTORS
