# Generated by Django 4.0.7 on 2022-10-15 15:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.TextField(choices=[('BSC', 'Binance Smart Chain'), ('SOL', 'Solana'), ('POLYGON', 'Polygon'), ('ETH', 'Ethereum'), ('TON', 'The Open Network')])),
                ('content', models.FileField(upload_to='nft/content', validators=[django.core.validators.FileExtensionValidator({'mp4', 'mp3', 'png', 'webp', 'gif'})])),
                ('sales_policy', models.TextField(choices=[('FIXED', 'Fixed price'), ('BET', 'Open for betting'), ('AUCTION', 'Temporary auction')])),
                ('price_currency', djmoney.models.fields.CurrencyField(choices=[('ETH', 'Ethereum')], default='ETH', editable=False, max_length=3)),
                ('price', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=10)),
                ('title', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]+$')])),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True, default='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
