# Generated by Django 4.0.7 on 2022-10-24 08:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collections', '0002_alter_collection_options_remove_collection_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nft',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('blockchain_address', models.CharField(blank=True, max_length=64, null=True)),
                ('network', models.TextField(choices=[('BSC', 'Binance Smart Chain'), ('SOL', 'Solana'), ('POLYGON', 'Polygon'), ('ETH', 'Ethereum'), ('TON', 'The Open Network')])),
                ('content', models.FileField(upload_to='nft/content', validators=[django.core.validators.FileExtensionValidator({'png', 'mp4', 'mp3', 'webp', 'gif'})])),
                ('title', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]+$')])),
                ('description', models.TextField(blank=True, default='')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collections.collection')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfts_by_creator', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfts_by_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
    ]
