# Generated by Django 4.1.2 on 2022-10-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_username_alter_user_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(
                blank=True, default=None, max_length=150, null=True, unique=True
            ),
        ),
    ]
