# Generated by Django 4.1.3 on 2022-11-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_avatar_user_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='second_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='third_score',
            field=models.IntegerField(default=0),
        ),
    ]
