version: '3.9'

services:
  db:
    extends:
      file: docker-compose.base.yml
      service: db
    volumes:
      - db_volume:/var/lib/postgresql/data
  redis:
    extends:
      file: docker-compose.base.yml
      service: redis
  api:
    extends:
      file: docker-compose.base.yml
      service: api
    env_file:
      - ../envs/.stage.env
    volumes:
      - profile_volume:/api/profile
      - /home/www/${COMPOSE_PROJECT_NAME}/media:/api/media
    command: bash -c "
      python manage.py migrate
      && python manage.py collectstatic --noinput
      && daphne -b 0.0.0.0 -p 8000 api.asgi:application
      "
    networks:
      - nginx_network
    depends_on:
      - db
      - redis
  celery:
    extends:
      file: docker-compose.base.yml
      service: celery
    depends_on:
      - api
  celery_beat:
    extends:
      file: docker-compose.base.yml
      service: celery_beat
    depends_on:
      - celery
  nginx:
    extends:
      file: docker-compose.base.yml
      service: nginx
    env_file:
      - ../envs/.stage.env
    ports:
      - 8080:8080
    volumes:
      - ../nginx/nginx.stage.conf.conf:/etc/nginx/templates/nginx.conf.conf:ro
      - static_volume:/etc/nginx/html/static
      - media_volume:/etc/nginx/html/media
    depends_on:
      - api

volumes:
  db_volume:
  profile_volume:
  static_volume:
  media_volume:

networks:
  db_network:
  redis_network:
  nginx_network:
