version: '3.9'

services:
  db:
    extends:
      file: ../docker-compose.base.yml
      service: db
    env_file: [ ../../envs/.prod.env ]
    ports: [ 5432:5432 ]
    volumes:
      - /home/www/nft-marketplace/db:/var/lib/postgresql/data
  redis:
    extends:
      file: ../docker-compose.base.yml
      service: redis
    env_file: [ ../../envs/.prod.env ]
  api:
    extends:
      file: ../docker-compose.base.yml
      service: api
    image: ghcr.io/codepandoradev/nft-marketplace-api/api:${TAG}
    env_file: [ ../../envs/.prod.env ]
    volumes:
      - /home/www/nft-marketplace/media:/api/media
      - static_volume:/api/static
    command: bash -c "
      python manage.py migrate
      && python manage.py collectstatic --noinput
      && daphne -b 0.0.0.0 -p 8000 api.asgi:application
      "
    networks: [ nginx_network ]
    depends_on: [ db, redis ]
  celery:
    extends:
      file: ../docker-compose.base.yml
      service: celery
    image: ghcr.io/codepandoradev/nft-marketplace-api/api:${TAG}
    env_file: [ ../../envs/.prod.env ]
    depends_on: [ api ]
  celery_beat:
    extends:
      file: ../docker-compose.base.yml
      service: celery_beat
    image: ghcr.io/codepandoradev/nft-marketplace-api/api:${TAG}
    env_file: [ ../../envs/.prod.env ]
    depends_on: [ celery ]
  nginx:
    extends:
      file: ../docker-compose.base.yml
      service: nginx
    build:
      dockerfile: ../nginx/prod.dockerfile
      args: [ TAG ]
    env_file: [ ../../envs/.prod.env ]
    ports: [ 80:80, 443:443 ]
    volumes:
      - /home/www/nft-marketplace/media:/etc/nginx/html/media
      - static_volume:/etc/nginx/html/static
    depends_on: [ api ]

volumes:
  static_volume:

networks:
  db_network:
  redis_network:
  nginx_network:
