name: "Area PR"

on:
  - pull_request

permissions:
  contents: read
  pull-requests: write

jobs:
  triage:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/labeler@v4.0.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
