name: Deploy stage

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [ self-hosted, nft-marketplace ]
    environment:
      name: stage
      url: 'http://stage.wonderplace.io:81'
    steps:
    - uses: actions/checkout@v3.1.0
      with:
        clean: false
    - name: Set stage envs
      run: echo "${{ secrets.STAGE_ENVS }}" > envs/.stage.env
    - name: Deploy stage environment
      run: docker-compose -p nft-marketplace-stage -f docker/stage/docker-compose.stage.yml up --build -d
