name: Deploy stage

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [ self-hosted, nft-marketplace ]
    steps:
    - uses: actions/checkout@v3.1.0
      with:
        clean: false
    - name: Deploy stage environment
      run: docker-compose -p nft-marketplace-stage -f docker/stage/docker-compose.stage.yml up --build -d
