name: CD prod

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

jobs:
  deploy:
    runs-on: [self-hosted, nft-marketplace]
    steps:
    - uses: actions/checkout@v3.1.0
      with:
        clean: false
    - name: Deploy prod environment
      run:
        |
        export TAG=${{ inputs.tag }}
        docker-compose -p nft-marketplace-prod -f docker/docker-compose.prod.yml up --renew-anon-volumes --force-recreate --build -d
