name: "Issue: mark not_milestone"

on:
  issues:
    types: [ unlabeled, labeled, opened, reopened ]

jobs:
  masrk:
    runs-on: ubuntu-22.04
    steps:
      - name: Add label "not_milestone"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          repo=${{ github.repository }}
          number=${{ github.event.issue.number }}
          label=$(gh api repos/$repo/issues/$number/labels \
            --jq '.[] | select(.name == "task")'
          )
          milestone=$(gh api repos/$repo/issues/$number --jq .milestone)
          if [ -z $milestone ] && [ -n $label ]; then
            gh issue edit $number -R $repo --add-label not_milestone
          fi
