name: "Issue: mark not_milestone"

on:
  issues:
    types: [ unlabeled, labeled, opened, reopened, milestoned ]

jobs:
  masrk:
    runs-on: ubuntu-22.04
    steps:
      - name: Add label "not_milestone"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          repo=${{ github.repository }}
          number=${{ github.event.issue.number }}
          label=$(gh api repos/$repo/issues/$number/labels \
            --jq '.[] | select(.name == "task")'
          )
          milestone=$(gh api repos/$repo/issues/$number --jq .milestone)
          echo -e "label=$label\nmilestone=$milestone"
          if [ -z $milestone ] && [ -n $label ]; then
            echo mark
            gh issue edit $number -R $repo --add-label not_milestone
          else
            echo unmark
            gh issue edit $number -R $repo --remove-label not_milestone
          fi
