name: "PR: assign"

on:
  pull_request:
    types: [ opened, reopened ]

permissions:
  contents: read
  pull-requests: write

jobs:
  assign:
    runs-on: ubuntu-22.04
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.4
