name: "PR: check labels"

on:
  pull_request:
    types: [ labeled, unlabeled, opened, reopened, synchronize ]

permissions:
  contents: read
  pull-requests: write

jobs:
  check:
    name: Check labels
    runs-on: ubuntu-22.04
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          one_of: task,test,bug,enhancement,dependencies,cicd
          repo_token: ${{ secrets.GITHUB_TOKEN }}
