name: "PR: add reviewers"

on:
  pull_request:
    types: opened

jobs:
  add:
    runs-on: ubuntu-22.04
    steps:
    - name: Add reviewers
      uses: madrapps/add-reviewers@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        reviewers: GentleEnvy
        re-request-when-changes-requested: true
