name: "Push: create PR"

on:
  push:
    branches:
      - task-*

jobs:
  create:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.2.0
      - name: Get task number
        id: get_task_number
        run: |
          branch_name=${GITHUB_REF##*/}
          val=${branch_name/task-/}
          if [[ ! $val =~ ^[[:digit:]]+$ ]]; then exit 0; fi
          echo VAL=$val >> $GITHUB_OUTPUT
      - name: Get author
        id: get_author
        run: |
          val=${{ github.event.commits[0].author.username }}
          upper=$(echo ${val^^})
          echo VAL=$val >> $GITHUB_OUTPUT
          echo UPPER=$upper >> $GITHUB_OUTPUT
      - name: Get token
        id: get_token
        run: |
          author=${{ steps.get_author.outputs.UPPER }}
          token=$(echo '${{ toJSON(secrets) }}' | \
            python -c \
            "import sys, json; print(json.load(sys.stdin).get ('${author}_TOKEN', ''))")
          echo $token
#          if [[ $token == "" ]]; then token=${{ secrets.TOKEN }}; fi
#          echo "VAL=$token" >> $GITHUB_OUTPUT
#      - uses: repo-sync/pull-request@v2.9
#        with:
#          pr_title: ${GITHUB_REF##*/}
#          pr_body: "close #${{ steps.get_task_number.output.VAL }}"
#          pr_assignee: ${{ github.event.commits[0].author.username }}
#          pr_draft: true
#          pr_allow_empty: true
#          github_token: ${{ steps.get_token.output.VAL }}
