name: "Push: tag"

on:
  push:
    tags:
      - '*'

permissions: write-all

jobs:
  ci:
    uses: ./.github/workflows/call-ci.yml
    secrets: inherit
  cd:
    uses: ./.github/workflows/call-deploy_prod.yml
    with:
      tag: ${{ github.ref_name }}
    secrets: inherit
    needs: [ci]
  sentry_release:
    uses: ./.github/workflows/call-sentry_release.yml
    with:
      environment: prod
      version: ${{ github.ref_name }}
    secrets: inherit
    needs: [ cd ]
