name: Push tag

on:
  push:
    tags:
      - '*'

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    secrets: inherit
  cd:
    uses: ./.github/workflows/cd-prod.yml
    with:
      tag: ${{ github.ref_name }}
    needs: [ci]
