name: Push master

on:
  push:
    branches:    
      - 'master'

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    secrets: inherit
  cd:
    uses: ./.github/workflows/cd-stage.yml
    needs: [ci]
