name: "Push: master"

on:
  push:
    branches:    
      - 'master'

permissions: write-all

jobs:
  ci:
    uses: ./.github/workflows/call-ci.yml
    secrets: inherit
  cd:
    uses: ./.github/workflows/call-deploy_stage.yml
    needs: [ ci ]
  release_draft:
    uses: ./.github/workflows/call-release_draft.yml
    secrets: inherit
    needs: [ ci ]
