name: "Push: master"

on:
  push:
    branches:    
      - 'master'

permissions: write-all

jobs:
  ci:
    uses: ./.github/workflows/call-ci.yml
    secrets: inherit
  build:
    uses: ./.github/workflows/call-build.yml
    secrets: inherit
    needs: [ ci ]
  cd:
    uses: ./.github/workflows/call-deploy_stage.yml
    secrets: inherit
    needs: [ build ]
  check_health:
    uses: ./.github/workflows/call-check_health.yml
    secrets: inherit
    needs: [ cd ]
  sentry_release:
    uses: ./.github/workflows/call-sentry_release.yml
    with:
      environment: stage
    secrets: inherit
    needs: [ cd ]
  update_prs:
    uses: ./.github/workflows/call-update_prs.yml
    secrets: inherit
    needs: [ ci ]
  release_draft:
    uses: ./.github/workflows/call-release_draft.yml
    secrets: inherit
    needs: [ update_prs ]
