name: "Push: not master"

on:
  push:
    branches-ignore:
      - 'master'

permissions: write-all

jobs:
  ci:
    uses: ./.github/workflows/call-ci.yml
    secrets: inherit
  update_prs:
    uses: ./.github/workflows/call-update_prs.yml
    secrets: inherit
